/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from "@react-three/drei"
import { useFrame, useThree } from "@react-three/fiber"

function useLerpedMouse() {
  const mouse = useThree((state) => state.mouse)
  const lerped = useRef(mouse.clone())
  const previous = new THREE.Vector2()
  useFrame((state) => {
    previous.copy(lerped.current)
    lerped.current.lerp(mouse, 0.1)
    // Regress system when the mouse is moved
    if (!previous.equals(lerped.current)) state.performance.regress()
  })
  return lerped
}

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Lvbu-final.glb')
  const mouse = useLerpedMouse()
  useFrame(state => {
    group.current.rotation.y = (mouse.current.x * Math.PI) / 10
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.shirt.geometry}
        material={nodes.shirt.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.belt.geometry}
        material={nodes.belt.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.body.geometry}
        material={nodes.body.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <group position={[0, 44.07, 4.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.71, 0.4, 1.71]}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['yellow emission']} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={nodes.Cylinder002_1.material} />
      </group>
      <mesh
        geometry={nodes.sharingan_button.geometry}
        material={nodes.sharingan_button.material}
        position={[1.66, 42.96, 4]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.3, 0.36, 0.3]}
      />
      <mesh
        geometry={nodes.body001.geometry}
        material={nodes.body001.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.body002.geometry}
        material={nodes.body002.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.body003.geometry}
        material={nodes.body003.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.between_chest.geometry}
        material={materials['chest-cf']}
        position={[0.04, 55.03, 3.85]}
        rotation={[-1.95, -1.57, 3.14]}
      />
      <mesh
        geometry={nodes.chest.geometry}
        material={nodes.chest.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials['side-cf']}
        position={[5.04, 56.47, 3.61]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.shoulder_.geometry}
        material={nodes.shoulder_.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.shoulder_001.geometry}
        material={nodes.shoulder_001.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.shoulder_002.geometry}
        material={nodes.shoulder_002.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.shoulder_003.geometry}
        material={nodes.shoulder_003.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <group position={[0.06, 57.35, -6.81]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.NurbsPath035.geometry} material={nodes.NurbsPath035.material} />
        <mesh geometry={nodes.NurbsPath035_1.geometry} material={nodes.NurbsPath035_1.material} />
      </group>
      <mesh
        geometry={nodes.cable002.geometry}
        material={materials['cable-cf']}
        position={[1.74, 58.23, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.butt_stripe1.geometry}
        material={materials['butt-stripe-cf']}
        position={[2.3, 38.06, -5.69]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.knee_guard003.geometry}
        material={materials['leg-guard-cf']}
        position={[3.59, 25.21, 3.54]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1.24, 1]}
      />
      <group position={[0, 66.5, 1.15]} scale={[1.02, 1.01, 1.01]}>
        <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} />
        <mesh geometry={nodes.Cube005_1.geometry} material={nodes.Cube005_1.material} />
        <mesh geometry={nodes.Cube005_2.geometry} material={nodes.Cube005_2.material} />
        <mesh geometry={nodes.Cube005_3.geometry} material={nodes.Cube005_3.material} />
      </group>
      <group position={[0, 66.5, 1.15]} scale={[1.02, 1.01, 1.01]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={nodes.Cube001_1.material} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['silver.001']} />
      </group>
      <mesh
        geometry={nodes.new_helmet002.geometry}
        material={nodes.new_helmet002.material}
        position={[0, 66.5, 1.15]}
        scale={[1.02, 1.01, 1.01]}
      />
      <mesh
        geometry={nodes.new_helmet003.geometry}
        material={nodes.new_helmet003.material}
        position={[0, 66.5, 1.15]}
        scale={[1.02, 1.01, 1.01]}
      />
      <mesh
        geometry={nodes.new_helmet004.geometry}
        material={nodes.new_helmet004.material}
        position={[0, 66.5, 1.15]}
        scale={[1.02, 1.01, 1.01]}
      />
      <mesh
        geometry={nodes.forearm.geometry}
        material={nodes.forearm.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.shoe.geometry}
        material={nodes.shoe.material}
        position={[3.45, 15.72, 1.32]}
        scale={[1.86, 1.73, 1.92]}
      />
      <group position={[3.45, 14.96, 1.4]} scale={[1.86, 1.73, 1.92]}>
        <mesh geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} />
        <mesh geometry={nodes.Plane014_1.geometry} material={materials['shoe-button-emmit']} />
      </group>
      <mesh
        geometry={nodes.shoe004.geometry}
        material={nodes.shoe004.material}
        position={[3.45, 14.3, 2.32]}
        scale={[1.86, 1.73, 1.92]}
      />
      <mesh
        geometry={nodes.shoe006.geometry}
        material={nodes.shoe006.material}
        position={[3.45, 14.3, 2.32]}
        scale={[1.86, 1.73, 1.92]}
      />
      <mesh
        geometry={nodes.shoe002.geometry}
        material={nodes.shoe002.material}
        position={[3.45, 14.3, 2.32]}
        scale={[1.86, 1.73, 1.92]}
      />
      <mesh
        geometry={nodes.shoe003.geometry}
        material={nodes.shoe003.material}
        position={[3.45, 14.3, 2.32]}
        scale={[1.86, 1.73, 1.92]}
      />
      <mesh
        geometry={nodes.shoe005.geometry}
        material={nodes.shoe005.material}
        position={[3.45, 14.3, 2.32]}
        scale={[1.86, 1.73, 1.92]}
      />
      <mesh
        geometry={nodes.shoe007.geometry}
        material={nodes.shoe007.material}
        position={[3.45, 15.72, 1.32]}
        scale={[1.86, 1.73, 1.92]}
      />
    </group>
  )
}

useGLTF.preload('/Lvbu-final.glb')
