/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import { useFrame, useThree } from "@react-three/fiber"

function useLerpedMouse() {
  const mouse = useThree((state) => state.mouse)
  const lerped = useRef(mouse.clone())
  const previous = new THREE.Vector2()
  useFrame((state) => {
    previous.copy(lerped.current)
    lerped.current.lerp(mouse, 0.1)
    // Regress system when the mouse is moved
    if (!previous.equals(lerped.current)) state.performance.regress()
  })
  return lerped
}

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/lvbu_cam_v4.glb")
  const { actions } = useAnimations(animations, group)
  const mouse = useLerpedMouse()
  useFrame(state => {
    group.current.rotation.y = (mouse.current.x * Math.PI) / 10
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.hand.geometry}
        material={materials.skin_tone_asian}
        position={[0.02, 0, -2.72]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.88, 0.99, 0.99]}
      />
      <mesh
        geometry={nodes.shirt.geometry}
        material={nodes.shirt.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.back_skirt.geometry}
        material={nodes.back_skirt.material}
        position={[0.18, 38.83, -4.79]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.front_skirt.geometry}
        material={nodes.front_skirt.material}
        position={[0, 42.6, 3.73]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.skirt.geometry}
        material={nodes.skirt.material}
        scale={[2.84, 7.99, 2.84]}
      />
      <mesh
        geometry={nodes.belt.geometry}
        material={nodes.belt.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.body.geometry}
        material={nodes.body.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <group
        position={[0, 44.07, 4.14]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.71, 0.4, 1.71]}
      >
        <mesh
          geometry={nodes.Cylinder002.geometry}
          material={materials["sharingan.emmision"]}
        />
        <mesh
          geometry={nodes.Cylinder002_1.geometry}
          material={nodes.Cylinder002_1.material}
        />
      </group>
      <mesh
        geometry={nodes.sharingan_button.geometry}
        material={nodes.sharingan_button.material}
        position={[1.66, 42.96, 4]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.3, 0.36, 0.3]}
      />
      <mesh
        geometry={nodes.between_chest.geometry}
        material={materials["carbon fiber"]}
        position={[0.04, 55.03, 3.85]}
        rotation={[-1.95, -1.57, 3.14]}
      />
      <mesh
        geometry={nodes.chest.geometry}
        material={nodes.chest.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials["carbon fiber.001"]}
        position={[5.04, 56.47, 3.61]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.shoulder_.geometry}
        material={nodes.shoulder_.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.back.geometry}
        material={nodes.back.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <group position={[0.06, 57.35, -6.81]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh
          geometry={nodes.NurbsPath035.geometry}
          material={materials["blue emission"]}
        />
        <mesh
          geometry={nodes.NurbsPath035_1.geometry}
          material={nodes.NurbsPath035_1.material}
        />
      </group>
      <mesh
        geometry={nodes.cable004.geometry}
        material={materials["carbon fiber.002"]}
        position={[3.29, 58.13, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.helmet.geometry}
        material={nodes.helmet.material}
        position={[0, 66.5, 1.15]}
        scale={[1.02, 1.01, 1.01]}
      />
      <mesh
        geometry={nodes.spec001.geometry}
        material={materials["yellow emission"]}
        position={[0, 66.5, 1.15]}
        scale={[1.02, 1.01, 1.01]}
      />
      <mesh
        geometry={nodes.hair.geometry}
        material={materials["red emission"]}
        position={[1.36, 75.1, 1.27]}
        rotation={[-0.01, 0, -0.32]}
        scale={[0.68, 0.97, 0.77]}
      />
      <mesh
        geometry={nodes.helmet_acc.geometry}
        material={nodes.helmet_acc.material}
        position={[0, 66.5, 1.15]}
        scale={[1.02, 1.01, 1.01]}
      />
      <mesh
        geometry={nodes.forearm.geometry}
        material={nodes.forearm.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.shoe.geometry}
        material={nodes.shoe.material}
        position={[3.45, 15.72, 1.32]}
        scale={[1.86, 1.73, 1.92]}
      />
      <mesh
        geometry={nodes.shoe001.geometry}
        material={nodes.shoe001.material}
        position={[3.45, 14.96, 1.4]}
        scale={[1.86, 1.73, 1.92]}
      />
      <mesh
        geometry={nodes.shoe002.geometry}
        material={nodes.shoe002.material}
        position={[3.45, 14.91, 0.99]}
        scale={[1.86, 1.73, 1.92]}
      />
      <mesh
        geometry={nodes.shoe003.geometry}
        material={nodes.shoe003.material}
        position={[3.45, 14.3, 2.32]}
        scale={[1.86, 1.73, 1.92]}
      />
      <mesh
        geometry={nodes.shoe004.geometry}
        material={nodes.shoe004.material}
        position={[3.45, 14.3, 2.32]}
        scale={[1.86, 1.73, 1.92]}
      />
      <mesh
        geometry={nodes.shoe005.geometry}
        material={nodes.shoe005.material}
        position={[3.45, 15.72, 0.99]}
        scale={[1.86, 1.73, 1.92]}
      />
      <mesh
        geometry={nodes.shoe006.geometry}
        material={nodes.shoe006.material}
        position={[3.45, 14.3, 2.32]}
        scale={[1.86, 1.73, 1.92]}
      />
      <mesh
        geometry={nodes.shoe007.geometry}
        material={nodes.shoe007.material}
        position={[5.98, 16.78, -2.12]}
        rotation={[-2.74, 1.41, 2.79]}
        scale={[1.86, 1.73, 1.92]}
      />
    </group>
  )
}

useGLTF.preload("/lvbu_cam_v4.glb")
