/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/lvbu_cam_v2.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Realistic_White_Male_Low_Poly.geometry}
        material={materials.skin_tone_asian}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.helmet.geometry}
        material={nodes.helmet.material}
        position={[0, 66.5, 1.15]}
        scale={[1.02, 1.01, 1.01]}
      />
      <mesh
        geometry={nodes.hat_acc.geometry}
        material={nodes.hat_acc.material}
        position={[0, 66.5, 1.15]}
        scale={[1.02, 1.01, 1.01]}
      />
      <mesh
        geometry={nodes.hair.geometry}
        material={materials['red emission']}
        position={[1.36, 75.1, 1.27]}
        rotation={[-0.01, 0, -0.32]}
        scale={[0.68, 0.97, 0.77]}
      />
      <mesh
        geometry={nodes.spec001.geometry}
        material={nodes.spec001.material}
        position={[0, 66.5, 1.15]}
        scale={[1.02, 1.01, 1.01]}
      />
      <mesh
        geometry={nodes.shirt.geometry}
        material={nodes.shirt.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.chest.geometry}
        material={nodes.chest.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.body.geometry}
        material={nodes.body.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.shoulder_.geometry}
        material={nodes.shoulder_.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.back.geometry}
        material={nodes.back.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.forearm.geometry}
        material={nodes.forearm.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh
        geometry={nodes.belt.geometry}
        material={nodes.belt.material}
        position={[0.01, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.89, 1, 1]}
      />
      <mesh geometry={nodes.skirt.geometry} material={nodes.skirt.material} scale={[2.84, 7.99, 2.84]} />
      <mesh
        geometry={nodes.front_skirt.geometry}
        material={nodes.front_skirt.material}
        position={[0, 42.6, 3.73]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <group position={[0, 44.07, 4.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.71, 0.4, 1.71]}>
        <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[0.06, 57.35, -6.81]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.NurbsPath035.geometry} material={materials['blue emission']} />
        <mesh geometry={nodes.NurbsPath035_1.geometry} material={nodes.NurbsPath035_1.material} />
      </group>
      <mesh
        geometry={nodes.cable002.geometry}
        material={nodes.cable002.material}
        position={[1.74, 58.23, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.cable003.geometry}
        material={nodes.cable003.material}
        position={[2.46, 58.24, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.cable004.geometry}
        material={nodes.cable004.material}
        position={[3.29, 58.13, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.cable005.geometry}
        material={nodes.cable005.material}
        position={[2.86, 58.37, 0.01]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.between_chest.geometry}
        material={nodes.between_chest.material}
        position={[0.04, 55.03, 3.85]}
        rotation={[-1.95, -1.57, 3.14]}
      />
      <mesh
        geometry={nodes.knee_guard002.geometry}
        material={nodes.knee_guard002.material}
        position={[3.59, 22.45, 2.81]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1.11, 1]}
      />
      <mesh
        geometry={nodes.knee_guard003.geometry}
        material={nodes.knee_guard003.material}
        position={[3.59, 25.21, 3.54]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1.24, 1]}
      />
      <mesh
        geometry={nodes.back_skirt.geometry}
        material={nodes.back_skirt.material}
        position={[0.18, 38.83, -4.79]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sharingan_button.geometry}
        material={nodes.sharingan_button.material}
        position={[1.66, 42.96, 4]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.3, 0.36, 0.3]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[5.04, 56.47, 3.61]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[5.04, 56.47, 3.61]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/lvbu_cam_v2.glb')
